name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select env to run
        options: 
        - dev
        - qa1
        - qa2
        - qa3 
        - staging
 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "hello ${{ inputs.environment }}" 
    - name: Determine role
      uses: haya14busa/action-cond@v1
      id: fetchRole
      with:
        cond: ${{ inputs.environment == 'staging' }}
        if_false: arn:aws:iam::373673428400:role/gha-role-gsm-cleanup-${{ inputs.environment }}
        if_true: arn:aws:iam::267474594073:role/gha-role-gsm-cleanup-staging
    # - name: Configure AWS creds for the specific env / region / app
    #   uses: aws-actions/configure-aws-credentials@master
    #   with:
    #     role-to-assume: ${{ steps.fetchRole.outputs.value }}
    #     role-session-name: deploysession
    #     aws-region: us-west-2
    - name: Send greeting    
      run: echo "hello ${{ inputs.environment }} is using ${{ steps.fetchRole.outputs.value  }} "  


      
           

    