name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select env to run
        options: 
        - dev
        - qa1
        - qa2
        - qa3 
        - staging
      payload:
        type: choice
        description: Select Payload
        options: 
        - Clear Synchronizer execution history table
        - Clear ApplicationConfiguration service entries
        - Clear GlobalStringLibrary tables data  
 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "hello ${{ inputs.environment }}" 
    - name: Determine role
      uses: haya14busa/action-cond@v1
      id: fetchRole
      with:
        cond: ${{ inputs.environment == 'staging' }}
        if_false: arn:aws:iam::373673428400:role/gha-role-gsm-cleanup-${{ inputs.environment }}
        if_true: arn:aws:iam::267474594073:role/gha-role-gsm-cleanup-staging
    - name: Send greeting    
      run: echo "hello ${{ inputs.environment }} is using ${{ steps.fetchRole.outputs.value  }} and running ${{ inputs.payload }} " 
    - name: Clear Synchronizer
      if: ${{ inputs.payload == 'Clear Synchronizer execution history table' }}
      run: echo "Clear Synchronizer"
    - name: Clear GlobalString
      if: ${{ inputs.payload == 'Clear GlobalStringLibrary tables data' }}
      run: echo "Clear GlobalString"
    - name: Clear Appconfig
      if: ${{ inputs.payload == 'Clear ApplicationConfiguration service entries' }}
      run: echo "Clear Appconfig"  


      
           

    